### ISSUE TITLE
Problem with registering data resource via UI in Kubernetes environment

### ISSUE THREAD

**Issue by SujitThonse** [International-Data-Spaces-Association/DataspaceConnectorUI#118]
# Steps to recreate the issue

### Deployments:
1. Deploy the provider and consumer connector in Kubernetes.
2. Deploy DSC-UI in Kubernetes with following .env variables
      - CONNECTOR_URL=https://example-provider-connector-onkubernetes.com
      - UI_TITLE=Dataspace Connector
      - CONNECTOR_USER=admin123
      - CONNECTOR_PASSWORD=somesecurepassword
   
Please note: We have not added env for backend URL in the above example as per the following [closed issue ](https://github.com/International-Data-Spaces-Association/DataspaceConnectorUI/issues/87#issuecomment-898671463)

## Data Upload Preferred Method
1. Upload JSON data on the provider side using DSC-UI eg.:https://api.oceandrivers.com/v1.0/getAemetStation/frankfurt/lastday/ 

Observation:
1. We can see that the UI can read the data which is already present in the connector and can also add the data
![image](https://user-images.githubusercontent.com/85099386/139415307-c6cd939a-c961-4e25-9e8b-52bec2132527.jpeg)

2. But on the Consumer side, payload is empty. And we are not able to download the artifact. 

## Data Upload Alternate Method Via Script

1. Using this python [script](https://github.com/SujitThonse/uploadDataToDSCV6.x/tree/main) we can register data resource to DSC V6.

Observation:
1. We can see the in the provider side UI the newly registered resource is visible.
2. On the consumer side we are able to download the artifact. 

### Remarks

- For DSC-UI, data upload / download process works perfectly fine in local docker setup. But only in the Kubernetes environment we are facing this issue. 
- We have also experimented by setting 'VUE_APP_UI_BACKEND_URL' to url of deployed DSC-UI in Kubernetes. But still we are facing same issues.

**Comment by BastianWel** [comment]
The problem already exists on the provider side and not only when consuming the data.
When the resource is created by UI, the data from the backend connection does not arrive in the Artifact. 
There seems to be a problem with PUT /api/artifacts/{id}/data:
```
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Http responseCode: 200
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - http-outgoing-0 << "{"TEMPERATURE": {}, "TWD": {"0": 315, "1": 315, "2": 270, "3": 315, "4": 315, "5": 315, "6": 360, "7": 45, "8": 45, "9": 0, "10": 360, "11": 45, "12": 0, "13": 0, "14": 90, "15": 90, "16": 45, "17": 90, "18": 315, "19": 0, "20": 45, "21": 225, "22": 0, "23": 45}, "TWS": {"0": 3.611111111111111, "1": 4.166666666666667, "2": 2.2222222222222223, "3": 1.6666666666666665, "4": 3.888888888888889, "5": 3.333333333333333, "6": 3.888888888888889, "7": 3.0555555555555554, "8": 3.333333333333333, "9": 0.0, "10": 1.9444444444444444, "11": 2.2222222222222223, "12": 0.0, "13": 0.0, "14": 1.6666666666666665, "15": 3.888888888888889, "16": 9.722222222222221, "17": 6.111111111111111, "18": 3.0555555555555554, "19": 0.0, "20": 0.8333333333333333, "21": 1.1111111111111112, "22": 0.0, "23": 1.9444444444444444}, "TIMESTAMP": {}, "LATEST_DATA": {"TEMPERATURE": 4.5, "TWD": 45, "PRESSURE": 1012.4, "RAIN_MONTH": 0, "TWS_GUST": 2.5, "RAIN_DAY": 0, "RAIN": 0.0, "HUMIDITY": 100.0, "TWS": 1.9444444444444444, "TIME_STRING": "03/12/2021 06:00", "TWD_GUST": 45, "TIME": 1638507600000, "LATITUDE": 39.5604, "LONGITUDE": 2.7417, "LOCALTIME": 1}, "RAIN": {"0": 0.0, "1": 0.0, "2": 0.0, "3": 0.0, "4": 0.0, "5": 0.0, "6": 0.0, "7": 0.9, "8": 0.0, "9": 0.4, "10": 0.2, "11": 0.0, "12": 0.0, "13": 0.0, "14": 0.0, "15": 0.3, "16": 0.4, "17": 0.8, "18": 0.0, "19": 0.0, "20": 0.0, "21": 0.3, "22": 0.3, "23": 0.0}, "HUMIDITY": {"0": 72.0, "1": 68.0, "2": 66.0, "3": 69.0, "4": 66.0, "5": 67.0, "6": 66.0, "7": 82.0, "8": 84.0, "9": 95.0, "10": 94.0, "11": 98.0, "12": 99.0, "13": 100.0, "14": 100.0, "15": 96.0, "16": 91.0, "17": 95.0, "18": 95.0, "19": 99.0, "20": 100.0, "21": 98.0, "22": 100.0, "23": 100.0}, "PRESSURE": {"0": 1005.1, "1": 1004.7, "2": 1005.6, "3": 1005.8, "4": 1006.0, "5": 1006.0, "6": 1005.6, "7": 1005.7, "8": 1006.0, "9": 1006.5, "10": 1007.3, "11": 1008.3, "12": 1009.1, "13": 1009.5, "14": 1009.9, "15": 1010.5, "16": 1012.1, "17": 1011.9, "18": 1012.2, "19": 1012.3, "20": 1012.4, "21": 1012.2, "22": 1012.2, "23": 1012.4}, "length": 60, "TIME": {"0": 1638424800000, "1": 1638428400000, "2": 1638432000000, "3": 1638435600000, "4": 1638439200000, "5": 1638442800000, "6": 1638446400000, "7": 1638450000000, "8": 1638453600000, "9": 1638457200000, "10": 1638460800000, "11": 1638464400000, "12": 1638468000000, "13": 1638471600000, "14": 1638475200000, "15": 1638478800000, "16": 1638482400000, "17": 1638486000000, "18": 1638489600000, "19": 1638493200000, "20": 1638496800000, "21": 1638500400000, "22": 1638504000000, "23": 1638507600000}}"
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Connection [id: 0][route: {s}->https://api.oceandrivers.com:443] can be kept alive for 5.0 seconds
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - http-outgoing-0: set socket timeout to 0
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Connection released: [id: 0][route: {s}->https://api.oceandrivers.com:443][total available: 1; route allocated: 1 of 2; total allocated: 1 of 20]
[Camel (camel-1) thread #0 - timer://foo] [32mINFO[m - Fetched data: {"TEMPERATURE": {}, "TWD": {"0": 315, "1": 315, "2": 270, "3": 315, "4": 315, "5": 315, "6": 360, "7": 45, "8": 45, "9": 0, "10": 360, "11": 45, "12": 0, "13": 0, "14": 90, "15": 90, "16": 45, "17": 90, "18": 315, "19": 0, "20": 45, "21": 225, "22": 0, "23": 45}, "TWS": {"0": 3.611111111111111, "1": 4.166666666666667, "2": 2.2222222222222223, "3": 1.6666666666666665, "4": 3.888888888888889, "5": 3.333333333333333, "6": 3.888888888888889, "7": 3.0555555555555554, "8": 3.333333333333333, "9": 0.0, "10": 1.9444444444444444, "11": 2.2222222222222223, "12": 0.0, "13": 0.0, "14": 1.6666666666666665, "15": 3.888888888888889, "16": 9.722222222222221, "17": 6.111111111111111, "18": 3.0555555555555554, "19": 0.0, "20": 0.8333333333333333, "21": 1.1111111111111112, "22": 0.0, "23": 1.9444444444444444}, "TIMESTAMP": {}, "LATEST_DATA": {"TEMPERATURE": 4.5, "TWD": 45, "PRESSURE": 1012.4, "RAIN_MONTH": 0, "TWS_GUST": 2.5, "RAIN_DAY": 0, "RAIN": 0.0, "HUMIDITY": 100.0, "TWS": 1.9444444444444444, "TIME_STRING": "03/12/2021 06:00", "TWD_GUST": 45, "TIME": 1638507600000, "LATITUDE": 39.5604, "LONGITUDE": 2.7417, "LOCALTIME": 1}, "RAIN": {"0": 0.0, "1": 0.0, "2": 0.0, "3": 0.0, "4": 0.0, "5": 0.0, "6": 0.0, "7": 0.9, "8": 0.0, "9": 0.4, "10": 0.2, "11": 0.0, "12": 0.0, "13": 0.0, "14": 0.0, "15": 0.3, "16": 0.4, "17": 0.8, "18": 0.0, "19": 0.0, "20": 0.0, "21": 0.3, "22": 0.3, "23": 0.0}, "HUMIDITY": {"0": 72.0, "1": 68.0, "2": 66.0, "3": 69.0, "4": 66.0, "5": 67.0, "6": 66.0, "7": 82.0, "8": 84.0, "9": 95.0, "10": 94.0, "11": 98.0, "12": 99.0, "13": 100.0, "14": 100.0, "15": 96.0, "16": 91.0, "17": 95.0, "18": 95.0, "19": 99.0, "20": 100.0, "21": 98.0, "22": 100.0, "23": 100.0}, "PRESSURE": {"0": 1005.1, "1": 1004.7, "2": 1005.6, "3": 1005.8, "4": 1006.0, "5": 1006.0, "6": 1005.6, "7": 1005.7, "8": 1006.0, "9": 1006.5, "10": 1007.3, "11": 1008.3, "12": 1009.1, "13": 1009.5, "14": 1009.9, "15": 1010.5, "16": 1012.1, "17": 1011.9, "18": 1012.2, "19": 1012.3, "20": 1012.4, "21": 1012.2, "22": 1012.2, "23": 1012.4}, "length": 60, "TIME": {"0": 1638424800000, "1": 1638428400000, "2": 1638432000000, "3": 1638435600000, "4": 1638439200000, "5": 1638442800000, "6": 1638446400000, "7": 1638450000000, "8": 1638453600000, "9": 1638457200000, "10": 1638460800000, "11": 1638464400000, "12": 1638468000000, "13": 1638471600000, "14": 1638475200000, "15": 1638478800000, "16": 1638482400000, "17": 1638486000000, "18": 1638489600000, "19": 1638493200000, "20": 1638496800000, "21": 1638500400000, "22": 1638504000000, "23": 1638507600000}}
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - >>>> https://localhost:8080/api/artifacts/e0d5a3e2-21c4-42ba-9399-591e69ef38c6/data Exchange[]
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Executing http PUT method: https://localhost:8080/api/artifacts/e0d5a3e2-21c4-42ba-9399-591e69ef38c6/data
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - CookieSpec selected: default
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Auth cache not set in the context
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Connection request: [route: {s}->https://localhost:8080][total available: 1; route allocated: 0 of 2; total allocated: 1 of 20]
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Connection leased: [id: 1][route: {s}->https://localhost:8080][total available: 1; route allocated: 1 of 2; total allocated: 2 of 20]
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Opening connection {s}->https://localhost:8080
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Connecting to localhost/127.0.0.1:8080
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Connecting socket to localhost/127.0.0.1:8080 with timeout 0
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Enabled protocols: [TLSv1.3, TLSv1.2]
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Enabled cipher suites:[TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Starting handshake
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Secure session established
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m -  negotiated protocol: TLSv1.3
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m -  negotiated cipher suite: TLS_AES_128_GCM_SHA256
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m -  peer principal: CN=f24e0a03-8fd2-4ef7-98d8-9d02e92a5f15, OU=PE, O=SAP, C=DE
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m -  peer alternative names: [provider.dsc-v6.ids-dev.shoot.canary.k8s-hana.ondemand.com]
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m -  issuer principal: CN=IDS Test SubCA 2018, O=Fraunhofer, C=DE
[Camel (camel-1) thread #0 - timer://foo] [34mDEBUG[m - Certificate for <localhost> doesn't match any of the subject alternative names: [provider.dsc-v6.ids-dev.shoot.canary.k8s-hana.ondemand.com]
javax.net.ssl.SSLPeerUnverifiedException: Certificate for <localhost> doesn't match any of the subject alternative names: [provider.dsc-v6.ids-dev.shoot.canary.k8s-hana.ondemand.com]
atchDNSName(DefaultHostnameVerifier.java:177) ~[httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.conn.ssl.DefaultHostnameVerifier.verify(DefaultHostnameVerifier.java:122) ~[httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.conn.ssl.DefaultHostnameVerifier.verify(DefaultHostnameVerifier.java:99) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:503) [httpclient-4.5.13.jar!/:4.5.13]
ateLayeredSocket(SSLConnectionSocketFactory.java:437) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) [httpclient-4.5.13.jar!/:4.5.13]
ator.java:142) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) [httpclient-4.5.13.jar!/:4.5.13]
at org.apache.camel.component.http.HttpProducer.executeMethod(HttpProducer.java:447) [camel-http-3.12.0.jar!/:3.12.0]
at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:275) [camel-http-3.12.0.jar!/:3.12.0]
at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66) [camel-support-3.12.0.jar!/:3.12.0]
at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:172) [camel-core-processor-3.12.0.jar!/:3.12.0]
at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:810) [camel-core-processor-3.12.0.jar!/:3.12.0]
at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:718) [camel-core-processor-3.12.0.jar!/:3.12.0]
at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:179) [camel-base-engine-3.12.0.jar!/:3.12.0]
at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:64) [camel-base-engine-3.12.0.jar!/:3.12.0]
at org.apache.camel.processor.Pipeline.process(Pipeline.java:184) [camel-core-processor-3.12.0.jar!/:3.12.0]
at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:399) [camel-base-engine-3.12.0.jar!/:3.12.0]
at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:210) [camel-timer-3.12.0.jar!/:3.12.0]
at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76) [camel-timer-3.12.0.jar!/:3.12.0]
at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
at java.util.TimerThread.run(Timer.java:506) [?:?]
```

**Comment by BastianWel** [comment]
Closing this issue here, because it is not an UI problem.
There seems to be a problem with certificates in the DSC.
If the problem persists, please create an issue in the DSC repository.
