### ISSUE TITLE
External datasource cannot be created

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#264]
Steps to reproduce:
1. Create a new resource
2. On the "Representation" page in create an external resource of type REST with basic authentication -> fails

When the dialog for creating the external resource is closed, the following error occurs in the DSC log:

```
java.lang.NullPointerException: Cannot invoke "String.getBytes()" because "message" is null
	at de.fraunhofer.iais.eis.ids.jsonld.Parser.readMessage(Parser.java:1101) ~[infomodel-serializer-4.2.8.jar:?]
	at de.fraunhofer.iais.eis.ids.jsonld.Parser.parseMessage(Parser.java:1085) ~[infomodel-serializer-4.2.8.jar:?]
	at de.fraunhofer.iais.eis.ids.jsonld.Serializer.deserialize(Serializer.java:120) ~[infomodel-serializer-4.2.8.jar:?]
	at io.dataspaceconnector.common.ids.DeserializationService.getContractAgreement(DeserializationService.java:205) ~[classes/:8.0.1]
	at io.dataspaceconnector.service.usagecontrol.ScheduledDataRemoval.scanAgreements(ScheduledDataRemoval.java:103) ~[classes/:8.0.1]
	at io.dataspaceconnector.service.usagecontrol.ScheduledDataRemoval.schedule(ScheduledDataRemoval.java:83) ~[classes/:8.0.1]
	at jdk.internal.reflect.GeneratedMethodAccessor293.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.22.jar:5.3.22]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by sebplorenz** [comment]
I realized that I have a general problem with my connector. The message from above does not only appear when creating representations. After deleting the database it everything works just fine. I close this issue.
